excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://eme0159.github.io
title: Prdx
email: emre.designs@Gmail.com
author: Emre Erdogan
description: Complicating moments of reasoning to Simplify concepts. 
paginate: 3
google_analytics: 